# **AIN 214 - PA1 - FALL 2024**

**Student Number** : 

**Name Surname**   : Barış Çelik


BELOW MD CELLS CONTAIN THE QUESTIONS YOU ARE ASKED TO IMPLEMENT WITHIN THE CONTEXT OF THIS HW. PLEASE FILL IN THE CELLS FOR THE ANSWERS RIGHT BELOW THE MD CELL OF THE QUESTION. YOU CAN ADD AS MANY CELLS AS YOU WANT, BE IT CODE OR MD, SO LONG AS YOU PROVIDE AN UNDERSTANDABLE AND TRACBLE REPORTING. PLEASE ADD COMMENTS ON YOUR CODES. ALSO, FILL IN MD CELLS WHERE YOU ARE ASKED YO COMMENT ON YOUR RESULTS OR EPXLAIN YOUR REASONING. ALSO, PLEASE DO NO HESITATE TO USE THEM FOR YOUR OWN REPORTING PURPOSES. PLEASE KEEP IN MIND THAT, REPORTING IS A KEY STEP IN DATA SCIENCE.

**Deadline: 18.10.2023 (23:59:59)**

**Submission:** Submit your Jupyter Notebooks via https://submit.cs.hacettepe.edu.tr/

# **Necessary Imports**

In [147]:
# Import required libraries
import numpy as np
import pandas as pd
import sqlite3
import seaborn as sns
import matplotlib.pyplot as plt

# **Notes:**

* Use pandas dataframe (df) to load the data.

* Use numpy or pandas operations for the requested tasks unless otherwise specified.

* Use of naive for loops is not considered valid.

* For the db operations, use sqlite3 library in Python

# **PART- 1**

**Set of Questions on World Happiness Report Dataset (40 Pts)**

**Dataset Path: "Data/WorldHappinessReport.csv"**

# Q1. Basic Data Exploration **(10 Pts)**

1. Load the data into Pandas DataFrame and print the column names. **(1 pts)**
2. Display the first and last 10 rows of the dataset. **(1 pts)**
3. Display random 10 rows. **(1 pts)**
4. Display random 10 rows with a seed, ie, it outputs the same random rows everytime it is run. **(1 pts)**
5. Display every 10th row. **(1 pts)**
6. Get the summary stats of the dataset regarding each column. **(2 pts)**
7. Identify and count the number of missing values in each column. **(3 pts)**

In [148]:
#1 Load the data into Pandas DataFrame and print the column names
df = pd.read_csv('Data/WorldHappinessReport.csv')

for col in df.columns:
    print(col)

Overall rank
Country or region
Score
GDP per capita
Social support
Healthy life expectancy
Freedom to make life choices
Generosity
Perceptions of corruption

In [149]:
#2 Display the first and last 10 rows of the dataset.

sliced_df = pd.concat([df.head(10), df.tail(10)])
print(sliced_df)

     Overall rank         Country or region  Score  GDP per capita  \
0               1                   Finland  7.632           1.305
1               2                    Norway  7.594           1.456
2               3                   Denmark  7.555           1.351
3               4                   Iceland  7.495           1.343
4               5               Switzerland  7.487           1.420
5               6               Netherlands  7.441           1.361
6               7                    Canada  7.328           1.330
7               8               New Zealand  7.324           1.268
8               9                    Sweden  7.314           1.355
9              10                 Australia  7.272           1.340
146           147                    Malawi  3.587           0.186
147           148                     Haiti  3.582           0.315
148           149                   Liberia  3.495           0.076
149           150                     Syria  3.462           0.689
150           151                    Rwanda  3.408           0.332
151           152                     Yemen  3.355           0.442
152           153                  Tanzania  3.303           0.455
153           154               South Sudan  3.254           0.337
154           155  Central African Republic  3.083           0.024
155           156                   Burundi  2.905           0.091

     Social support  Healthy life expectancy  Freedom to make life choices  \
0             1.592                    0.874                         0.681
1             1.582                    0.861                         0.686
2             1.590                    0.868                         0.683
3             1.644                    0.914                         0.677
4             1.549                    0.927                         0.660
5             1.488                    0.878                         0.638
6             1.532                    0.896                         0.653
7             1.601                    0.876                         0.669
8             1.501                    0.913                         0.659
9             1.573                    0.910                         0.647
146           0.541                    0.306                         0.531
147           0.714                    0.289                         0.025
148           0.858                    0.267                         0.419
149           0.382                    0.539                         0.088
150           0.896                    0.400                         0.636
151           1.073                    0.343                         0.244
152           0.991                    0.381                         0.481
153           0.608                    0.177                         0.112
154           0.000                    0.010                         0.305
155           0.627                    0.145                         0.065

     Generosity  Perceptions of corruption
0         0.202                      0.393
1         0.286                      0.340
2         0.284                      0.408
3         0.353                      0.138
4         0.256                      0.357
5         0.333                      0.295
6         0.321                      0.291
7         0.365                      0.389
8         0.285                      0.383
9         0.361                      0.302
146       0.210                      0.080
147       0.392                      0.104
148       0.206                      0.030
149       0.376                      0.144
150       0.200                      0.444
151       0.083                      0.064
152       0.270                      0.097
153       0.224                      0.106
154       0.218                      0.038
155       0.149                      0.076

In [150]:
#3 Display the random 10 rows
print(df.sample(10))

     Overall rank     Country or region  Score  GDP per capita  \
5               6           Netherlands  7.441           1.361
123           124                 Kenya  4.410           0.493
116           117                  Iraq  4.456           1.010
19             20  United Arab Emirates  6.774           2.096
124           125                Zambia  4.377           0.562
50             51              Slovenia  5.948           1.219
36             37              Colombia  6.260           0.960
78             79                Greece  5.358           1.154
70             71           Philippines  5.524           0.775
111           112               Albania  4.586           0.916

     Social support  Healthy life expectancy  Freedom to make life choices  \
5             1.488                    0.878                         0.638
123           1.048                    0.454                         0.504
116           0.971                    0.536                         0.304
19            0.776                    0.670                         0.284
124           1.047                    0.295                         0.503
50            1.506                    0.856                         0.633
36            1.439                    0.635                         0.531
78            1.202                    0.879                         0.131
70            1.312                    0.513                         0.643
111           0.817                    0.790                         0.419

     Generosity  Perceptions of corruption
5         0.333                      0.295
123       0.352                      0.055
116       0.148                      0.095
19        0.186                        NaN
124       0.221                      0.082
50        0.160                      0.051
36        0.099                      0.039
78        0.000                      0.044
70        0.120                      0.105
111       0.149                      0.032

In [151]:
#4 sample using seed (Display random 10 rows with a seed. it outputs the same random rows everytime it is run)

#set a seed value
seed_value = 3

# Randomly sample 10 rows from the dataframe using the seed value
random_sample = df.sample(n = 10, random_state = seed_value)
print(random_sample)

     Overall rank Country or region  Score  GDP per capita  Social support  \
139           140            Guinea  3.964           0.344           0.792
3               4           Iceland  7.495           1.343           1.644
25             26            Taiwan  6.441           1.365           1.436
102           103             Gabon  4.758           1.036           1.164
15             16           Belgium  6.927           1.324           1.483
51             52           Romania  5.945           1.116           1.219
148           149           Liberia  3.495           0.076           0.858
6               7            Canada  7.328           1.330           1.532
41             42            Poland  6.123           1.176           1.448
67             68      Turkmenistan  5.636           1.016           1.533

     Healthy life expectancy  Freedom to make life choices  Generosity  \
139                    0.211                         0.394       0.185
3                      0.914                         0.677       0.353
25                     0.857                         0.418       0.151
102                    0.404                         0.356       0.032
15                     0.894                         0.583       0.188
51                     0.726                         0.528       0.088
148                    0.267                         0.419       0.206
6                      0.896                         0.653       0.321
41                     0.781                         0.546       0.108
67                     0.517                         0.417       0.199

     Perceptions of corruption
139                      0.094
3                        0.138
25                       0.078
102                      0.052
15                       0.240
51                       0.001
148                      0.030
6                        0.291
41                       0.064
67                       0.037

In [152]:
#5 Display every 10th row
# a:b:c , c determines step size, and a is the first 10th
print(df.iloc[9::10, :])

     Overall rank     Country or region  Score  GDP per capita  \
9              10             Australia  7.272           1.340
19             20  United Arab Emirates  6.774           2.096
29             30             Guatemala  6.382           0.781
39             40           El Salvador  6.167           0.806
49             50             Lithuania  5.952           1.197
59             60            Kazakhstan  5.790           1.143
69             70                 Libya  5.566           0.985
79             80               Lebanon  5.358           0.965
89             90                Jordan  5.161           0.822
99            100              Bulgaria  4.933           1.054
109           110                  Laos  4.623           0.720
119           120              Cambodia  4.433           0.549
129           130               Myanmar  4.308           0.682
139           140                Guinea  3.964           0.344
149           150                 Syria  3.462           0.689

     Social support  Healthy life expectancy  Freedom to make life choices  \
9             1.573                    0.910                         0.647
19            0.776                    0.670                         0.284
29            1.268                    0.608                         0.604
39            1.231                    0.639                         0.461
49            1.527                    0.716                         0.350
59            1.516                    0.631                         0.454
69            1.350                    0.553                         0.496
79            1.179                    0.785                         0.503
89            1.265                    0.645                         0.468
99            1.515                    0.712                         0.359
109           1.034                    0.441                         0.626
119           1.088                    0.457                         0.696
129           1.174                    0.429                         0.580
139           0.792                    0.211                         0.394
149           0.382                    0.539                         0.088

     Generosity  Perceptions of corruption
9         0.361                      0.302
19        0.186                        NaN
29        0.179                      0.071
39        0.065                      0.082
49        0.026                      0.006
59        0.148                      0.121
69        0.116                      0.148
79        0.214                      0.136
89        0.130                      0.134
99        0.064                      0.009
109       0.230                      0.174
119       0.256                      0.065
129       0.598                      0.178
139       0.185                      0.094
149       0.376                      0.144

In [153]:
#6 Get the summary stats of the dataset regarding each column
# we can get couple of information using .describe() 
df.describe()

,Overall rank,Score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
count,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,156.000000,155.000000
mean,78.500000,5.375917,0.891449,1.213237,0.597346,0.454506,0.181006,0.112000
std,45.177428,1.119506,0.391921,0.302372,0.247579,0.162424,0.098471,0.096492
min,1.000000,2.905000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,39.750000,4.453750,0.616250,1.066750,0.422250,0.356000,0.109500,0.051000
50%,78.500000,5.378000,0.949500,1.255000,0.644000,0.487000,0.174000,0.082000
75%,117.250000,6.168500,1.197750,1.463000,0.777250,0.578500,0.239000,0.137000
max,156.000000,7.632000,2.096000,1.644000,1.030000,0.724000,0.598000,0.457000

In [154]:
#7 Identify and count the number of missing values in each column

# .isna() find missing values

print(df['Overall rank'].isna().sum())
print(df['Country or region'].isna().sum())
print(df['Score'].isna().sum())
print(df['GDP per capita'].isna().sum())
print(df['Social support'].isna().sum())
print(df['Healthy life expectancy'].isna().sum())
print(df['Freedom to make life choices'].isna().sum())
print(df['Generosity'].isna().sum())
print(df['Perceptions of corruption'].isna().sum())

0
0
0
0
0
0
0
0
1

# Q2. Basic Data Statistics: **(10 Pts)**

1. Calculate the mean, median, and standard deviation of the happiness Score across all countries. **(1 Pts)**
2. Identify the top 5 happiest countries and the bottom 5 least happy countries based on happiness Score. **(1 Pts)**
3. Find the country with the highest Healthy Life Expectancy. What is the corresponding happiness Score? **(2 Pts)**
4. Calculate the average Corruption Perceptions for countries with a happiness Score greater than 6. **(2 Pts)**
5. Are there any countries where Generosity is higher than Social Support? List them. **(2 Pts)**
6. What is the range (max-min) of GDP per Capita values in the dataset? **(2 Pts)**

In [155]:
#1
# calculate mean median and std
mean_score = df['Score'].mean()
median_score = df['Score'].median()
std_dev_score = df['Score'].std()

print(mean_score)
print(median_score)
print(std_dev_score)

5.375916666666668
5.378
1.119505852731943

In [156]:
#2
# sort by Score, decreasing order
sorted_df = df.sort_values(by="Score", ascending=False) 

# Top 5 happiest countries
top_happy_countries = sorted_df.iloc[:5][['Country or region']]
print(top_happy_countries)

# Bottom 5 least happy countries
bottom_happy_countries = sorted_df.iloc[-5:][['Country or region']]
print(bottom_happy_countries)

  Country or region
0           Finland
1            Norway
2           Denmark
3           Iceland
4       Switzerland
            Country or region
151                     Yemen
152                  Tanzania
153               South Sudan
154  Central African Republic
155                   Burundi

In [157]:
#3 
# Find the country with the highest Healthy life expectancy
highest_life_expectancy = df[df['Healthy life expectancy'] == df['Healthy life expectancy'].max()]
highest_le_country = highest_life_expectancy[['Country or region']]
happiness_score_of = highest_life_expectancy[['Healthy life expectancy']]
# Display the country, healthy life expectancy, and the corresponding happiness score
print(highest_le_country)
print(happiness_score_of)

   Country or region
75         Hong Kong
    Healthy life expectancy
75                     1.03

In [158]:
#4 Calculate the average Corruption Perceptions for countries with a happiness Score greater than 6.
# filter by happiness score
country_greater_than6 = df[df['Score'] > 6]

# Calculate the average perceptions of corruption for these countries
average_corruption = country_greater_than6['Perceptions of corruption'].mean()
print(average_corruption)

0.1782888888888889

In [159]:
#5 Are there any countries where Generosity is higher than Social Support? List them.
#filter
country_gHs = df[df['Generosity'] > df['Social support']]
for i in country_gHs['Country or region']:
    print(i)

Central African Republic

In [160]:
#6 What is the range (max-min) of GDP per Capita values in the dataset?
gdp_range = df['GDP per capita'].max() - df['GDP per capita'].min()

print(gdp_range)

2.096

# Q3. Data Filtering **(20 Pts)**

1. How many countries have a Happiness Score greater than 7.5? List their names.**(2 Pts)**
2. List all countries where the Corruption Perception score is below 0.2. **(2 Pts)**
3. Filter and list the top 5 countries by Generosity. What is their average Happiness Score? **(2 Pts)**
4. Find countries where GDP per Capita is less than 0.5 but the Happiness Score is above 4. List the countries. **(2 Pts)**
5. Filter countries where Social Support is higher than Freedom to Make Life **(2 Pts)**
6. Find countries in the top 10% of Healthy Life Expectancy and list their names. **(2 Pts)**
7. Filter and list countries where Generosity is less than Social Support. What is the average Happiness Score of these countries? **(2 Pts)**
8.  Find all countries with a Happiness Score below the median happiness score. How many are there, and what are the common characteristics of these countries? **(3 Pts)**
9. Filter countries where both Freedom to Make Life Choices and Healthy Life Expectancy are above the global median. How many such countries are there? **(3 Pts)**

In [161]:
#1
# filter by Score
hsgt_sevenpointfive = df[df['Score'] > 7.5]['Country or region']
# get size 
size_hsgt = hsgt_sevenpointfive.shape[0]
print(size_hsgt)
#list names
for i in hsgt_sevenpointfive:
    print(i)

3
Finland
Norway
Denmark

In [162]:
#2 List all countries where the Corruption Perception score is below 0.2.
cps_less = df[df['Perceptions of corruption'] < 0.2]['Country or region']
for i in cps_less:
    print(i)

Iceland
United Kingdom
Costa Rica
United States
Czech Republic
Malta
France
Mexico
Chile
Taiwan
Panama
Brazil
Argentina
Guatemala
Uruguay
Qatar
Saudi Arabia
Malaysia
Spain
Colombia
Trinidad & Tobago
Slovakia
El Salvador
Nicaragua
Poland
Bahrain
Kuwait
Thailand
Italy
Ecuador
Belize
Lithuania
Slovenia
Romania
Latvia
Japan
Mauritius
Jamaica
South Korea
Northern Cyprus
Russia
Kazakhstan
Cyprus
Bolivia
Estonia
Paraguay
Peru
Kosovo
Moldova
Turkmenistan
Hungary
Libya
Philippines
Honduras
Belarus
Turkey
Pakistan
Portugal
Serbia
Greece
Lebanon
Montenegro
Croatia
Dominican Republic
Algeria
Morocco
China
Azerbaijan
Tajikistan
Macedonia
Jordan
Nigeria
Kyrgyzstan
Bosnia and Herzegovina
Mongolia
Vietnam
Indonesia
Bhutan
Cameroon
Bulgaria
Nepal
Venezuela
Gabon
Palestinian Territories
South Africa
Iran
Ivory Coast
Ghana
Senegal
Laos
Tunisia
Albania
Sierra Leone
Congo (Brazzaville)
Bangladesh
Sri Lanka
Iraq
Mali
Namibia
Cambodia
Burkina Faso
Egypt
Mozambique
Kenya
Zambia
Mauritania
Ethiopia
Armenia
Myanmar
Chad
Congo (Kinshasa)
India
Niger
Uganda
Benin
Sudan
Ukraine
Togo
Guinea
Lesotho
Angola
Madagascar
Zimbabwe
Afghanistan
Botswana
Malawi
Haiti
Liberia
Syria
Yemen
Tanzania
South Sudan
Central African Republic
Burundi

In [163]:
#3 Filter and list the top 5 countries by Generosity. What is their average Happiness Score?
sorted_df = df.sort_values(by="Generosity", ascending=False) #sort by decreasing order
# get top 5
top_gen = sorted_df.iloc[:5][['Country or region', 'Score']]
for i in top_gen['Country or region']:
    print(i)

#calculate average happiness score
average_hs = top_gen['Score'].mean()
print(average_hs)

Myanmar
Indonesia
Haiti
Syria
Malta
4.6144

In [164]:
#4 Find countries where GDP per Capita is less than 0.5 but the Happiness Score is above 4. List the countries
#filter
filter_by_gdp_score = df[(df['GDP per capita'] < 0.5) & (df['Score'] > 4)]
#list that countries
for i in filter_by_gdp_score['Country or region']:
    print(i)

Tajikistan
Somalia
Nepal
Senegal
Sierra Leone
Mali
Burkina Faso
Mozambique
Kenya
Ethiopia
Chad
Congo (Kinshasa)
Niger
Uganda
Benin

In [165]:
#5 Filter countries where Social Support is higher than Freedom to Make Life
#filter
sp_higher_f = df[df['Social support'] > df['Freedom to make life choices']]
for i in sp_higher_f['Country or region']:
    print(i)

Finland
Norway
Denmark
Iceland
Switzerland
Netherlands
Canada
New Zealand
Sweden
Australia
United Kingdom
Austria
Costa Rica
Ireland
Germany
Belgium
Luxembourg
United States
Israel
United Arab Emirates
Czech Republic
Malta
France
Mexico
Chile
Taiwan
Panama
Brazil
Argentina
Guatemala
Uruguay
Qatar
Saudi Arabia
Singapore
Malaysia
Spain
Colombia
Trinidad & Tobago
Slovakia
El Salvador
Nicaragua
Poland
Bahrain
Uzbekistan
Kuwait
Thailand
Italy
Ecuador
Belize
Lithuania
Slovenia
Romania
Latvia
Japan
Mauritius
Jamaica
South Korea
Northern Cyprus
Russia
Kazakhstan
Cyprus
Bolivia
Estonia
Paraguay
Peru
Kosovo
Moldova
Turkmenistan
Hungary
Libya
Philippines
Honduras
Belarus
Turkey
Pakistan
Hong Kong
Portugal
Serbia
Greece
Lebanon
Montenegro
Croatia
Dominican Republic
Algeria
Morocco
China
Azerbaijan
Tajikistan
Macedonia
Jordan
Nigeria
Kyrgyzstan
Bosnia and Herzegovina
Mongolia
Vietnam
Indonesia
Bhutan
Somalia
Cameroon
Bulgaria
Nepal
Venezuela
Gabon
Palestinian Territories
South Africa
Iran
Ivory Coast
Ghana
Senegal
Laos
Tunisia
Albania
Sierra Leone
Congo (Brazzaville)
Bangladesh
Sri Lanka
Iraq
Mali
Namibia
Cambodia
Burkina Faso
Egypt
Mozambique
Kenya
Zambia
Mauritania
Ethiopia
Georgia
Armenia
Myanmar
Chad
Congo (Kinshasa)
India
Niger
Uganda
Sudan
Ukraine
Togo
Guinea
Lesotho
Angola
Madagascar
Zimbabwe
Afghanistan
Botswana
Malawi
Haiti
Liberia
Syria
Rwanda
Yemen
Tanzania
South Sudan
Burundi

In [166]:
#6 Find countries in the top 10% of Healthy Life Expectancy and list their names.

# Sort the DataFrame by Healthy Life Expectancy in descending order
sorted_df = df.sort_values(by='Healthy life expectancy', ascending=False)

# Calculate the number of countries
num_countries = sorted_df.shape[0]

# Select the top 10% of countries based on Healthy Life Expectancy
top_10_percent_countries = sorted_df.iloc[:int(num_countries * 0.1)][['Country or region']]

# List the names of these countries
top_10_percent_countries_list = top_10_percent_countries['Country or region'].tolist()
print(top_10_percent_countries_list)

['Hong Kong', 'Singapore', 'Japan', 'Spain', 'South Korea', 'Italy', 'Switzerland', 'Iceland', 'Sweden', 'Australia', 'Northern Cyprus', 'Cyprus', 'France', 'Luxembourg', 'Canada']

In [167]:
#7 Filter and list countries where Generosity is less than Social Support. 
#What is the average Happiness Score of these countries?

# Filter countries where Generosity is less than Social Support
generosity_less_than_support = df[df['Generosity'] < df['Social support']]

# Get a list of countries where Generosity is less than Social Support
list_gen_less_than_supp = generosity_less_than_support['Country or region'].tolist()
print(list_gen_less_than_supp)

# Calculate the average Happiness Score of these countries
average_happiness_score = generosity_less_than_support['Score'].mean()
print(average_happiness_score)

['Finland', 'Norway', 'Denmark', 'Iceland', 'Switzerland', 'Netherlands', 'Canada', 'New Zealand', 'Sweden', 'Australia', 'United Kingdom', 'Austria', 'Costa Rica', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United States', 'Israel', 'United Arab Emirates', 'Czech Republic', 'Malta', 'France', 'Mexico', 'Chile', 'Taiwan', 'Panama', 'Brazil', 'Argentina', 'Guatemala', 'Uruguay', 'Qatar', 'Saudi Arabia', 'Singapore', 'Malaysia', 'Spain', 'Colombia', 'Trinidad & Tobago', 'Slovakia', 'El Salvador', 'Nicaragua', 'Poland', 'Bahrain', 'Uzbekistan', 'Kuwait', 'Thailand', 'Italy', 'Ecuador', 'Belize', 'Lithuania', 'Slovenia', 'Romania', 'Latvia', 'Japan', 'Mauritius', 'Jamaica', 'South Korea', 'Northern Cyprus', 'Russia', 'Kazakhstan', 'Cyprus', 'Bolivia', 'Estonia', 'Paraguay', 'Peru', 'Kosovo', 'Moldova', 'Turkmenistan', 'Hungary', 'Libya', 'Philippines', 'Honduras', 'Belarus', 'Turkey', 'Pakistan', 'Hong Kong', 'Portugal', 'Serbia', 'Greece', 'Lebanon', 'Montenegro', 'Croatia', 'Dominican Republic', 'Algeria', 'Morocco', 'China', 'Azerbaijan', 'Tajikistan', 'Macedonia', 'Jordan', 'Nigeria', 'Kyrgyzstan', 'Bosnia and Herzegovina', 'Mongolia', 'Vietnam', 'Indonesia', 'Bhutan', 'Somalia', 'Cameroon', 'Bulgaria', 'Nepal', 'Venezuela', 'Gabon', 'Palestinian Territories', 'South Africa', 'Iran', 'Ivory Coast', 'Ghana', 'Senegal', 'Laos', 'Tunisia', 'Albania', 'Sierra Leone', 'Congo (Brazzaville)', 'Bangladesh', 'Sri Lanka', 'Iraq', 'Mali', 'Namibia', 'Cambodia', 'Burkina Faso', 'Egypt', 'Mozambique', 'Kenya', 'Zambia', 'Mauritania', 'Ethiopia', 'Georgia', 'Armenia', 'Myanmar', 'Chad', 'Congo (Kinshasa)', 'India', 'Niger', 'Uganda', 'Benin', 'Sudan', 'Ukraine', 'Togo', 'Guinea', 'Lesotho', 'Angola', 'Madagascar', 'Zimbabwe', 'Afghanistan', 'Botswana', 'Malawi', 'Haiti', 'Liberia', 'Syria', 'Rwanda', 'Yemen', 'Tanzania', 'South Sudan', 'Burundi']
5.390709677419356

In [168]:
#8Find all countries with a Happiness Score below the median happiness score. 
#How many are there, and what are the common characteristics of these countries?

# Filter countries with a Happiness Score below the median
countries_below_median = df[df['Score'] < (df['Score'].median())]
for i in countries_below_median['Country or region']:
    print(i)


# Count the number of countries
number_of_countries_below_median = countries_below_median['Country or region'].shape[0]
print(number_of_countries_below_median)

# Analyze common characteristics (Mostly underdeveloped and developing countries)
common_characteristics = countries_below_median.describe()
print(common_characteristics)
# common characteristics are low healthy life expectancy,GDP per capita and social support.

Greece
Lebanon
Montenegro
Croatia
Dominican Republic
Algeria
Morocco
China
Azerbaijan
Tajikistan
Macedonia
Jordan
Nigeria
Kyrgyzstan
Bosnia and Herzegovina
Mongolia
Vietnam
Indonesia
Bhutan
Somalia
Cameroon
Bulgaria
Nepal
Venezuela
Gabon
Palestinian Territories
South Africa
Iran
Ivory Coast
Ghana
Senegal
Laos
Tunisia
Albania
Sierra Leone
Congo (Brazzaville)
Bangladesh
Sri Lanka
Iraq
Mali
Namibia
Cambodia
Burkina Faso
Egypt
Mozambique
Kenya
Zambia
Mauritania
Ethiopia
Georgia
Armenia
Myanmar
Chad
Congo (Kinshasa)
India
Niger
Uganda
Benin
Sudan
Ukraine
Togo
Guinea
Lesotho
Angola
Madagascar
Zimbabwe
Afghanistan
Botswana
Malawi
Haiti
Liberia
Syria
Rwanda
Yemen
Tanzania
South Sudan
Central African Republic
Burundi
78
       Overall rank      Score  GDP per capita  Social support  \
count     78.000000  78.000000       78.000000       78.000000
mean     117.500000   4.449321        0.621256        1.019423
std       22.660538   0.623645        0.308177        0.288077
min       79.000000   2.905000        0.000000        0.000000
25%       98.250000   4.139500        0.357250        0.860250
50%      117.500000   4.451500        0.623500        1.083000
75%      136.750000   4.980250        0.910500        1.215000
max      156.000000   5.358000        1.154000        1.517000

       Healthy life expectancy  Freedom to make life choices  Generosity  \
count                78.000000                     78.000000   78.000000
mean                  0.432962                      0.386885    0.176705
std                   0.221797                      0.169637    0.105170
min                   0.000000                      0.000000    0.000000
25%                   0.254250                      0.283000    0.112250
50%                   0.423000                      0.419000    0.174000
75%                   0.612750                      0.515500    0.219500
max                   0.879000                      0.696000    0.598000

       Perceptions of corruption
count                  78.000000
mean                    0.088295
std                     0.064311
min                     0.000000
25%                     0.052000
50%                     0.077500
75%                     0.105500
max                     0.444000

In [169]:
#9 Filter countries where both Freedom to Make Life Choices and Healthy Life Expectancy are above the global median.
#How many such countries are there? 

# Filter countries where both values are above their respective medians
both_above = df[(df['Freedom to make life choices'] > df['Freedom to make life choices'].median()) & 
                         (df['Healthy life expectancy'] > df['Healthy life expectancy'].median())]

print(both_above.shape[0])

47

# **PART- 2**

**Set of Questions on the passenger_demographics.csv and passenger_survival.csv** **(25 Pts)**

**Dataset Path: "Data/passenger_demographics.csv" and "Data/passenger_survival.csv"**

# Q1. Data Merging and Consistency Checking


1. Merge the datasets on PassengerId into a single DataFrame. How many rows are there in the merged dataset? **(3 Pts)**
2. Perform a consistency check for duplicated rows. After merging, check for any duplicated rows in the merged dataset and provide a summary of your findings. Provide the details (average, mean, etc.) of each feature in the merged DataFrame. **(3 Pts)**
3. Determine the survival rate for each passenger class and gender. Analyze how the survival rate varies among different classes (Pclass) and genders. **(3 Pts)**
4. Analyze the effect of age on survival probability. Determine whether age significantly affects the probability of survival. Use statistical techniques to explore this relationship.(use binning) **(4 Pts)**
5. Investigate the impact of family size on survival. Determine if family size (based on the number of siblings/spouses and parents/children aboard) has any correlation with survival. **(4 Pts)**
6. Determine the most common embarkation point among survivors. Find out which embarkation point (C, Q, or S) had the highest survival rate. **(4 Pts)**
7. Evaluate the correlation between Fare and Survival. Determine if there is a correlation between the fare paid and the survival status of the passengers. **(4 Pts)**

In [170]:
#1
#merge datasets 
df1 = pd.read_csv('Data/passenger_demographics.csv')
df2 = pd.read_csv('Data/passenger_survival.csv')
df = pd.merge(df1, df2, on='PassengerId')

print(df.shape[0])
print(df)

891
     PassengerId  Pclass     Sex   Age  SibSp  Parch  Survived     Fare  \
0              1       3    male  22.0      1      0         0   7.2500
1              2       1  female  38.0      1      0         1  71.2833
2              3       3  female  26.0      0      0         1   7.9250
3              4       1  female  35.0      1      0         1  53.1000
4              5       3    male  35.0      0      0         0   8.0500
..           ...     ...     ...   ...    ...    ...       ...      ...
886          887       2    male  27.0      0      0         0  13.0000
887          888       1  female  19.0      0      0         1  30.0000
888          889       3  female   NaN      1      2         0  23.4500
889          890       1    male  26.0      0      0         1  30.0000
890          891       3    male  32.0      0      0         0   7.7500

    Embarked
0          S
1          C
2          S
3          S
4          S
..       ...
886        S
887        S
888        S
889        C
890        Q

[891 rows x 9 columns]

In [171]:
#2
#check for duplicate
duplicate_rows = df[df.duplicated()]
print(duplicate_rows)

# Summary statistics of the merged DataFrame
print(df.describe())

# Count of duplicate rows
print(duplicate_rows.shape[0])

Empty DataFrame
Columns: [PassengerId, Pclass, Sex, Age, SibSp, Parch, Survived, Fare, Embarked]
Index: []
       PassengerId      Pclass         Age       SibSp       Parch  \
count   891.000000  891.000000  714.000000  891.000000  891.000000
mean    446.000000    2.308642   29.699118    0.523008    0.381594
std     257.353842    0.836071   14.526497    1.102743    0.806057
min       1.000000    1.000000    0.420000    0.000000    0.000000
25%     223.500000    2.000000   20.125000    0.000000    0.000000
50%     446.000000    3.000000   28.000000    0.000000    0.000000
75%     668.500000    3.000000   38.000000    1.000000    0.000000
max     891.000000    3.000000   80.000000    8.000000    6.000000

         Survived        Fare
count  891.000000  891.000000
mean     0.383838   32.204208
std      0.486592   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      1.000000   31.000000
max      1.000000  512.329200
0

In [172]:
#3 Determine the survival rate for each passenger class and gender. Analyze how the survival rate varies 
# among different classes (Pclass) and genders.,

# Calculating survival rate for each class and gender
survival_rates = df.groupby(['Pclass', 'Sex'])['Survived'] 
print(survival_rates.describe())

# rate of alive decreasing towards from 1 to 3 and from man to woman

               count      mean       std  min  25%  50%  75%  max
Pclass Sex
1      female   94.0  0.968085  0.176716  0.0  1.0  1.0  1.0  1.0
       male    122.0  0.368852  0.484484  0.0  0.0  0.0  1.0  1.0
2      female   76.0  0.921053  0.271448  0.0  1.0  1.0  1.0  1.0
       male    108.0  0.157407  0.365882  0.0  0.0  0.0  0.0  1.0
3      female  144.0  0.500000  0.501745  0.0  0.0  0.5  1.0  1.0
       male    347.0  0.135447  0.342694  0.0  0.0  0.0  0.0  1.0

In [173]:
#4 Analyze the effect of age on survival probability. Determine whether age significantly affects the probability of survival
#Use statistical techniques to explore this relationship.(use binning)

# Binning the age data into categories
bins = [0, 18, 35, 50, 80]
labels = ['0-18', '19-35', '36-50', '51-80']
df['AgeGroup'] = pd.cut(df['Age'], bins=bins, labels=labels, include_lowest=True)

# Calculating the survival rate for each age group
age_survival_rate = df.groupby('AgeGroup')['Survived'].mean() * 100

# survival rate is the highest in the early age 
print(age_survival_rate)

AgeGroup
0-18     50.359712
19-35    38.268156
36-50    39.869281
51-80    34.375000
Name: Survived, dtype: float64

In [174]:
#5 Investigate the impact of family size on survival. Determine if family size (based on the number of siblings/spouses
#and parents/children aboard) has any correlation with survival.

# Creating a new feature 'FamilySize' by adding 'SibSp' and 'Parch' to represent family size
df['FamilySize'] = df['SibSp'] + df['Parch']

# Calculating the survival rate for different family sizes
family_size_survival_rate = df.groupby('FamilySize')['Survived'].mean() * 100

# When I look at the infos, survival rate increasing until 3 after that decreasing
print(family_size_survival_rate)

FamilySize
0     30.353818
1     55.279503
2     57.843137
3     72.413793
4     20.000000
5     13.636364
6     33.333333
7      0.000000
10     0.000000
Name: Survived, dtype: float64

In [175]:
#6 Determine the most common embarkation point among survivors. Find out which embarkation point (C, Q, or S) 
#had the highest survival rate.

# Calculating the survival rate for each embarkation point
embarkation_survival_rate = df.groupby('Embarked')['Survived'].mean() * 100

# Finding the embarkation point with the highest survival rate
most_common_embarkation_survivor = embarkation_survival_rate.idxmax()

# Displaying the survival rates and the most common embarkation point among survivors
print(embarkation_survival_rate)
print(most_common_embarkation_survivor)

Embarked
C    55.357143
Q    38.961039
S    33.695652
Name: Survived, dtype: float64
C

In [176]:
#7 7. Evaluate the correlation between Fare and Survival. Determine if there is a correlation between the fare paid
#and the survival status of the passengers. **(4 Pts)**

# Calculating the correlation between 'Fare' and 'Survived'
fare_survival_correlation = df['Fare'].corr(df['Survived'])

# Displaying the correlation result
print(fare_survival_correlation)
# correlation result is positive, that means there is a correlation between fare and Survival

0.25730652238496243

# **PART- 3**

**Set of Questions on SQL - using sqlite3 library!**

**Dataset Path: "Data/supermarket_sales.csv"**


The Supermarket Sales Dataset is a comprehensive dataset designed to provide insights into the sales performance of a supermarket.

We want to store this data in a relational database, with the following table schemas:

# Tables

## 1. Branches Table

| Column   | Type  | Key      | Description                              |
|----------|-------|----------|------------------------------------------|
| BranchID | INTEGER  | PRIMARY  | Unique identifier for each branch        |
| Branch | TEXT  |            |    Name of the supermarket branch        |
| City     | TEXT  |          | City where the branch is located         |



## 2. Products Table

| Column      | Type  | Key      | Description                               |
|-------------|-------|----------|-------------------------------------------|
| ProductID | INTEGER  | PRIMARY  | Unique identifier for each product line   |
| ProductLine | TEXT  |          | Category of the product |



## 3. Orders Table

| Column        | Type  | Key      | Description                                    |
|---------------|-------|----------|------------------------------------------------|
| OrderID       | TEXT  | PRIMARY  | Unique identifier for each order               |
| BranchID      | INTEGER  |   FK       | Identifier for the branch of the order    |
| ProductID   | INTEGER  |      FK    | Identifier linking to Products table ordered                      |
| Quantity      | INTEGER |        | Number of units ordered                        |
| UnitPrice   | REAL  |          | Price per unit of the product             |Total         | REAL  |          | Total sales value for the order               |
| OrderDate     | TEXT  |          | Date when the order was placed                |
| PaymentMethod | TEXT  |          | Method used for payment                       |
| CustomerType  | TEXT  |          | Type of customer (e.g., Member, Normal)     |
| Gender        | TEXT  |          | Gender of the customer                        |

Summary of Table Structures

* Branches Table contains information about different supermarket branches.

* Products Table details the various products available for purchase.
* Orders Table records the transactions made, linking products and branches to specific purchases.

# **Questions** **(35 Pts)**

1. Read the csv file and create this DB **(10 Pts)**
2. Write a query to find the top 3 product lines with the highest total quantity sold, using a LIMIT statement. **(4 Pts)**
3. Find the total revenue generated for each branch by product line **(4 Pts)**
4. Find the total sales for each branch **(3 Pts)**
5. Determine the number of orders placed by each gender **(3 Pts)**
6. List the product lines sold in each branch and the number of orders **(4 Pts)**
7. Find the highest quantity sold for a single order and the corresponding product line **(4 Pts)**
8. Check for duplicated invoices **(3 Pts)**

In [177]:
#1
# Load the CSV data into a pandas DataFrame
data = pd.read_csv("Data/supermarket_sales.csv")

# create and connect new db
conn = sqlite3.connect('supermarket_sales.db')
cursor = conn.cursor()


# Create the table structure based on the dataset
cursor.execute('''
CREATE TABLE IF NOT EXISTS sales (
    invoice_id TEXT,
    branch TEXT,
    city TEXT,
    customer_type TEXT,
    gender TEXT,
    product_line TEXT,
    unit_price REAL,
    quantity INTEGER,
    tax_5 REAL,
    total REAL,
    date TEXT,
    time TEXT,
    payment TEXT
)
''')

# Insert the CSV data into the SQLite table
for row in data.itertuples(index=False):
    cursor.execute('''
    INSERT INTO sales (invoice_id, branch, city, customer_type, gender, product_line, unit_price, quantity, tax_5, total, date, time, payment)
    VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
    ''', row)
    
# Commit changes
conn.commit()

In [178]:
#2
# Query to find the top 3 product lines with the highest total quantity sold
query_1 = '''
    SELECT product_line, SUM(quantity) AS total_quantity
    FROM sales
    GROUP BY product_line
    ORDER BY total_quantity DESC
    LIMIT 3;
'''
cursor.execute(query_1)
results_1 = cursor.fetchall()

for row in results_1:
    print(row)

('Electronic accessories', 7768)
('Food and beverages', 7624)
('Home and lifestyle', 7376)

In [179]:
#3
# Find the total revenue generated for each branch by product line
query_2 = '''
    SELECT branch, product_line, SUM(total) AS total_revenue
    FROM sales
    GROUP BY branch, product_line
    ORDER BY branch, total_revenue DESC;
'''
cursor.execute(query_2)
results_2 = cursor.fetchall()

for row in results_2:
    print(row)

('A', 'Home and lifestyle', 179890.4520000001)
('A', 'Sports and travel', 154981.59600000002)
('A', 'Electronic accessories', 146536.90799999994)
('A', 'Food and beverages', 137572.26000000013)
('A', 'Fashion accessories', 135854.45999999993)
('A', 'Health and beauty', 100782.02400000003)
('B', 'Sports and travel', 159905.59199999992)
('B', 'Health and beauty', 159845.27999999988)
('B', 'Home and lifestyle', 148573.23599999998)
('B', 'Electronic accessories', 136411.5480000001)
('B', 'Fashion accessories', 131306.532)
('B', 'Food and beverages', 121719.10800000011)
('C', 'Food and beverages', 190134.83999999982)
('C', 'Fashion accessories', 172480.55999999968)
('C', 'Electronic accessories', 151751.79599999994)
('C', 'Health and beauty', 133261.54799999998)
('C', 'Sports and travel', 126095.42399999978)
('C', 'Home and lifestyle', 111164.42399999994)

In [180]:
#4
# Find the total sales for each branch
query_3 = '''
    SELECT branch, SUM(total) AS total_sales
    FROM sales
    GROUP BY branch
    ORDER BY total_sales DESC;
'''
cursor.execute(query_3)
results_3 = cursor.fetchall()

for row in results_3:
    print(row)

('C', 884888.5920000032)
('B', 857761.2960000022)
('A', 855617.7000000007)

In [181]:
#5
# Determine the number of orders placed by each gender
query_4 = '''
    SELECT gender, COUNT(*) AS num_orders
    FROM sales
    GROUP BY gender;
'''
cursor.execute(query_4)
results_4 = cursor.fetchall()

for row in results_4:
    print(row)

('Female', 4024)
('Male', 4016)

In [182]:
#6
# List the product lines sold in each branch and the number of orders
query_5 = '''
    SELECT branch, product_line, COUNT(*) AS num_orders
    FROM sales
    GROUP BY branch, product_line
    ORDER BY branch, num_orders DESC;
'''
cursor.execute(query_5)
results_5 = cursor.fetchall()

for row in results_5:
    print(row)

('A', 'Home and lifestyle', 528)
('A', 'Electronic accessories', 480)
('A', 'Sports and travel', 472)
('A', 'Food and beverages', 472)
('A', 'Fashion accessories', 416)
('A', 'Health and beauty', 376)
('B', 'Sports and travel', 496)
('B', 'Fashion accessories', 496)
('B', 'Electronic accessories', 440)
('B', 'Health and beauty', 424)
('B', 'Home and lifestyle', 408)
('B', 'Food and beverages', 400)
('C', 'Food and beverages', 528)
('C', 'Fashion accessories', 520)
('C', 'Electronic accessories', 440)
('C', 'Health and beauty', 424)
('C', 'Sports and travel', 360)
('C', 'Home and lifestyle', 360)

In [183]:
#7
# Find the highest quantity sold for a single order and the corresponding product line
query_6 = '''
    SELECT product_line, MAX(quantity) AS max_quantity
    FROM sales;
'''
cursor.execute(query_6)
results_6 = cursor.fetchall()

for row in results_6:
    print(row)

('Home and lifestyle', 10)

In [184]:
#8

# Check duplicated invoices
query_7 = '''
    SELECT invoice_id, COUNT(*) AS count
    FROM sales
    GROUP BY invoice_id
    HAVING count > 1;
'''
cursor.execute(query_7)
results_7 = cursor.fetchall()

for row in results_7:
    print(row)

# Close the database connection
conn.close()

('101-17-6199', 8)
('101-81-4070', 8)
('102-06-2002', 8)
('102-77-2261', 8)
('105-10-6182', 8)
('105-31-1824', 8)
('106-35-6779', 8)
('109-28-2512', 8)
('109-86-4363', 8)
('110-05-6330', 8)
('110-48-7033', 8)
('114-35-5271', 8)
('115-38-7388', 8)
('115-99-4379', 8)
('118-62-1812', 8)
('120-06-4233', 8)
('120-54-2248', 8)
('122-61-9553', 8)
('123-19-1176', 8)
('123-35-4896', 8)
('124-31-1458', 8)
('125-45-2293', 8)
('126-54-1082', 8)
('127-47-6963', 8)
('129-29-8530', 8)
('130-67-4723', 8)
('130-98-8941', 8)
('131-15-8856', 8)
('131-70-8179', 8)
('132-23-6451', 8)
('132-32-9879', 8)
('133-14-7229', 8)
('133-77-3154', 8)
('134-54-4720', 8)
('134-75-2619', 8)
('135-13-8269', 8)
('135-84-8019', 8)
('136-08-6195', 8)
('137-63-5492', 8)
('137-74-8729', 8)
('138-17-5109', 8)
('139-20-0155', 8)
('139-32-4183', 8)
('139-52-2867', 8)
('142-63-6033', 8)
('142-72-4741', 8)
('144-51-6085', 8)
('145-94-9061', 8)
('146-09-5432', 8)
('148-41-7930', 8)
('148-82-2527', 8)
('149-14-0304', 8)
('149-15-7606', 8)
('149-61-1929', 8)
('149-71-6266', 8)
('150-89-8043', 8)
('151-16-1484', 8)
('151-27-8496', 8)
('151-33-7434', 8)
('152-03-4217', 8)
('152-08-9985', 8)
('152-68-2907', 8)
('153-58-4872', 8)
('154-74-7179', 8)
('154-87-7367', 8)
('155-45-3814', 8)
('156-20-0370', 8)
('156-95-3964', 8)
('157-13-5295', 8)
('160-22-2687', 8)
('162-48-8011', 8)
('162-65-8559', 8)
('163-56-7055', 8)
('166-19-2553', 8)
('169-52-4504', 8)
('172-42-8274', 8)
('173-50-1108', 8)
('173-57-2300', 8)
('173-82-9529', 8)
('174-36-3675', 8)
('174-64-0215', 8)
('174-75-0888', 8)
('175-54-2529', 8)
('176-64-7711', 8)
('176-78-1170', 8)
('181-82-6255', 8)
('181-94-6432', 8)
('182-52-7000', 8)
('182-69-8360', 8)
('182-88-2763', 8)
('183-21-3799', 8)
('183-56-6882', 8)
('186-09-3669', 8)
('186-43-8965', 8)
('186-71-5196', 8)
('186-79-9562', 8)
('187-83-5490', 8)
('188-55-0967', 8)
('189-08-9157', 8)
('189-17-4241', 8)
('189-40-5216', 8)
('189-52-0236', 8)
('189-55-2313', 8)
('189-98-2939', 8)
('190-14-3147', 8)
('190-59-3964', 8)
('191-10-6171', 8)
('191-29-0321', 8)
('192-98-7397', 8)
('195-06-0432', 8)
('196-01-2849', 8)
('197-77-7132', 8)
('198-66-9832', 8)
('198-84-7132', 8)
('199-75-8169', 8)
('200-16-5952', 8)
('200-40-6154', 8)
('201-63-8275', 8)
('201-86-2184', 8)
('207-73-1363', 8)
('209-61-0206', 8)
('210-30-7976', 8)
('210-57-1719', 8)
('210-67-5886', 8)
('210-74-9613', 8)
('211-05-0490', 8)
('211-30-9270', 8)
('212-62-1842', 8)
('213-32-1216', 8)
('213-72-6612', 8)
('214-17-6927', 8)
('214-30-2776', 8)
('217-58-1179', 8)
('218-59-9410', 8)
('219-22-9386', 8)
('219-61-4139', 8)
('220-28-1851', 8)
('220-68-6701', 8)
('221-25-5073', 8)
('222-42-0244', 8)
('225-32-0908', 8)
('225-98-1496', 8)
('226-31-3081', 8)
('226-34-0034', 8)
('226-71-3580', 8)
('227-03-5010', 8)
('227-07-4446', 8)
('227-50-3718', 8)
('227-78-1148', 8)
('228-96-1411', 8)
('232-11-3025', 8)
('232-16-2483', 8)
('233-34-0817', 8)
('233-67-5758', 16)
('234-03-4040', 8)
('234-36-2483', 8)
('234-65-2137', 8)
('235-06-8510', 8)
('235-46-8343', 8)
('236-27-1144', 8)
('236-86-3015', 8)
('237-01-6122', 8)
('237-44-6163', 8)
('238-45-6950', 8)
('238-49-0436', 8)
('239-10-7476', 8)
('239-36-3640', 8)
('239-48-4278', 8)
('241-11-2261', 8)
('241-72-9525', 8)
('241-96-5076', 8)
('242-11-3142', 8)
('242-55-6721', 8)
('243-47-2663', 8)
('243-55-8457', 8)
('244-08-0162', 8)
('246-11-3901', 8)
('246-55-6923', 8)
('247-11-2470', 8)
('249-42-3782', 8)
('250-17-5703', 8)
('250-81-7186', 8)
('252-56-2699', 8)
('253-12-6086', 8)
('254-31-0042', 8)
('256-08-8343', 8)
('256-58-3609', 8)
('257-60-7754', 8)
('257-73-1380', 8)
('258-69-7810', 8)
('258-92-7466', 8)
('261-12-8671', 8)
('262-47-2794', 8)
('263-10-3913', 8)
('263-12-5321', 8)
('263-87-5680', 8)
('266-20-6657', 8)
('266-76-6436', 8)
('267-62-7380', 8)
('268-03-6164', 8)
('268-20-3585', 8)
('268-27-6179', 8)
('269-04-5750', 8)
('269-10-8440', 8)
('271-77-8740', 8)
('271-88-8734', 8)
('272-27-9238', 8)
('272-65-1806', 8)
('273-16-6619', 8)
('273-84-2164', 8)
('274-05-5470', 8)
('275-28-0149', 8)
('276-54-0879', 8)
('276-75-6884', 8)
('277-35-5865', 8)
('277-63-2961', 8)
('278-86-2735', 8)
('278-97-7759', 8)
('279-62-1445', 8)
('279-74-2924', 8)
('280-17-4359', 8)
('280-35-5823', 8)
('282-35-2475', 8)
('283-26-5248', 8)
('283-79-9594', 8)
('284-34-9626', 8)
('284-54-4231', 8)
('285-68-5083', 8)
('286-01-5402', 8)
('286-43-6208', 8)
('286-62-6248', 8)
('286-75-7818', 8)
('287-21-9091', 8)
('287-83-1405', 8)
('288-38-3758', 8)
('288-62-1085', 8)
('289-15-7034', 8)
('289-65-5721', 8)
('290-68-2984', 8)
('291-21-5991', 8)
('291-32-1427', 8)
('291-55-6563', 8)
('291-59-1384', 8)
('296-11-7041', 8)
('299-29-0180', 8)
('299-46-1805', 8)
('300-71-4605', 8)
('301-11-9629', 8)
('301-81-8610', 8)
('302-15-2162', 8)
('303-96-2227', 16)
('305-03-2383', 8)
('305-14-0245', 8)
('305-18-3552', 8)
('305-89-2768', 8)
('307-04-2070', 8)
('307-83-9164', 8)
('307-85-2293', 8)
('308-39-1707', 8)
('308-47-4913', 8)
('308-81-0538', 8)
('311-13-6971', 8)
('313-66-9943', 8)
('314-23-4520', 8)
('315-22-5665', 8)
('316-01-3952', 8)
('316-55-4634', 8)
('316-66-3011', 8)
('316-68-6352', 8)
('318-12-0304', 8)
('318-68-5053', 8)
('318-81-2368', 8)
('319-50-3348', 8)
('319-74-2561', 8)
('320-32-8842', 8)
('320-49-6392', 8)
('320-85-2052', 8)
('321-49-7382', 8)
('322-02-2271', 8)
('324-41-6833', 8)
('324-92-3863', 8)
('325-77-6186', 8)
('325-89-4209', 8)
('325-90-8763', 8)
('326-71-2155', 8)
('326-78-5178', 8)
('327-40-9673', 8)
('329-62-1586', 8)
('333-23-2632', 8)
('333-73-7901', 8)
('334-64-2006', 8)
('336-78-2147', 8)
('338-65-2210', 8)
('339-12-4827', 8)
('339-18-7061', 8)
('339-38-9982', 8)
('339-96-8318', 8)
('340-21-9136', 8)
('340-66-0321', 8)
('342-65-4817', 8)
('343-61-3544', 8)
('343-75-9322', 8)
('343-87-0864', 8)
('345-08-4992', 8)
('345-68-9016', 8)
('346-12-3257', 8)
('346-84-3103', 8)
('347-34-2234', 8)
('347-56-2442', 16)
('347-72-6115', 8)
('349-97-8902', 8)
('351-62-0822', 8)
('354-25-5821', 8)
('354-39-5160', 8)
('355-34-6244', 8)
('355-53-5943', 8)
('356-44-8813', 8)
('358-88-9262', 8)
('359-90-3665', 8)
('359-94-5395', 8)
('360-39-5055', 8)
('361-59-0574', 8)
('361-85-2571', 8)
('362-58-8315', 8)
('364-33-8584', 8)
('364-34-2972', 8)
('365-16-4334', 8)
('365-64-0515', 8)
('366-43-6862', 8)
('366-93-0948', 8)
('369-82-2676', 8)
('370-41-7321', 8)
('370-96-0655', 8)
('371-85-5789', 8)
('372-26-1506', 8)
('372-62-5264', 8)
('372-94-8041', 8)
('373-09-4567', 8)
('373-14-0504', 8)
('373-73-7910', 8)
('373-88-1424', 8)
('374-17-3652', 8)
('374-38-5555', 8)
('375-72-3056', 8)
('376-02-8238', 8)
('376-56-3573', 8)
('377-79-7592', 8)
('378-07-7001', 8)
('378-24-2715', 8)
('379-17-6588', 8)
('380-60-5336', 8)
('380-94-4661', 8)
('381-20-0914', 8)
('382-03-4532', 8)
('382-25-8917', 8)
('384-59-6655', 8)
('386-27-7606', 8)
('387-49-4215', 8)
('388-76-2555', 8)
('389-25-3394', 8)
('389-70-2397', 8)
('390-17-5806', 8)
('390-31-6381', 8)
('390-80-5128', 8)
('393-65-2792', 8)
('394-30-3170', 8)
('394-41-0748', 8)
('394-43-4238', 8)
('394-55-6384', 8)
('396-90-2219', 8)
('397-25-8725', 8)
('399-46-5918', 8)
('399-69-4630', 8)
('400-45-1220', 8)
('400-60-7251', 8)
('400-80-4065', 8)
('400-89-4171', 8)
('401-09-4232', 8)
('401-18-8016', 8)
('404-91-5964', 8)
('405-31-3305', 8)
('406-46-7107', 8)
('407-63-8975', 8)
('408-26-9866', 8)
('408-66-6712', 8)
('409-33-9708', 8)
('409-49-6995', 8)
('410-67-1709', 8)
('411-77-0180', 8)
('413-20-6708', 8)
('414-12-7047', 8)
('416-13-5917', 8)
('416-17-9926', 8)
('418-02-5978', 8)
('418-05-0656', 8)
('420-04-7590', 8)
('420-11-4919', 8)
('420-18-8989', 8)
('420-97-3340', 8)
('421-95-9805', 8)
('422-29-8786', 8)
('423-57-2993', 8)
('423-64-4619', 8)
('423-80-0988', 8)
('425-85-2085', 8)
('426-39-2418', 8)
('427-45-9297', 8)
('428-83-5800', 8)
('430-02-3888', 8)
('430-53-4718', 8)
('430-60-3493', 8)
('431-66-2305', 8)
('433-08-7822', 8)
('433-75-6987', 8)
('434-35-9162', 8)
('434-83-9547', 8)
('435-13-4908', 8)
('436-54-4512', 8)
('437-53-3084', 8)
('437-58-8131', 8)
('438-01-4015', 8)
('438-23-1242', 8)
('439-54-7422', 8)
('440-59-5691', 8)
('441-94-7118', 8)
('442-44-6497', 8)
('442-48-3607', 8)
('443-59-0061', 8)
('443-60-9639', 8)
('443-82-0585', 8)
('445-30-9252', 8)
('446-47-6729', 8)
('447-15-7839', 8)
('448-34-8700', 8)
('448-61-3783', 8)
('448-81-5016', 8)
('449-16-6770', 8)
('449-27-2918', 8)
('450-28-2866', 8)
('450-42-3339', 8)
('451-28-5717', 8)
('451-73-2711', 8)
('452-04-8808', 8)
('453-12-7053', 8)
('453-33-6436', 8)
('453-63-6187', 8)
('457-12-0244', 8)
('457-13-1708', 8)
('457-94-0464', 8)
('458-10-8612', 8)
('458-41-1477', 8)
('458-61-0011', 8)
('459-45-2396', 8)
('459-50-7686', 8)
('460-35-4390', 8)
('460-93-5834', 8)
('462-67-9126', 8)
('462-78-5240', 8)
('466-61-5506', 8)
('468-01-2051', 8)
('468-88-0009', 8)
('468-99-7231', 8)
('470-31-3286', 8)
('470-32-9057', 8)
('471-06-8611', 8)
('471-41-2823', 8)
('472-15-9636', 8)
('474-33-8305', 8)
('477-24-6490', 8)
('477-59-2456', 8)
('478-06-7835', 8)
('479-26-8945', 8)
('480-63-2856', 8)
('482-17-1179', 8)
('483-71-1164', 8)
('484-22-8230', 8)
('485-30-8700', 8)
('487-79-6868', 8)
('488-25-4221', 8)
('489-64-4354', 8)
('489-82-1237', 8)
('490-29-1201', 8)
('490-95-0021', 8)
('491-38-3499', 8)
('493-65-6248', 8)
('497-36-0989', 8)
('497-37-6538', 8)
('498-41-1961', 8)
('499-27-7781', 8)
('500-02-2261', 8)
('501-61-1753', 8)
('502-05-1910', 8)
('503-07-0930', 8)
('503-21-4385', 8)
('504-35-8843', 8)
('505-02-0892', 8)
('509-10-0516', 8)
('509-29-3912', 8)
('510-09-5628', 8)
('510-79-0415', 8)
('510-95-6347', 8)
('511-54-3087', 8)
('512-91-0811', 8)
('512-98-1403', 8)
('514-37-2845', 8)
('516-77-6464', 8)
('518-17-2983', 8)
('518-71-6847', 8)
('521-18-7827', 8)
('522-57-8364', 8)
('523-38-0215', 8)
('525-09-8450', 8)
('525-88-7307', 8)
('526-86-8552', 8)
('527-09-6272', 8)
('528-14-9470', 8)
('528-87-5606', 8)
('529-56-3974', 8)
('530-90-9855', 8)
('531-56-4728', 8)
('531-80-1784', 8)
('532-59-7201', 8)
('533-33-5337', 8)
('533-66-5566', 8)
('534-01-4457', 8)
('534-53-3526', 8)
('537-72-0426', 8)
('538-22-0304', 8)
('539-21-7227', 8)
('540-11-4336', 8)
('541-08-3113', 8)
('541-48-8554', 8)
('541-89-9860', 8)
('542-41-0513', 8)
('544-32-5024', 8)
('544-55-9589', 8)
('545-07-8534', 8)
('545-46-3100', 8)
('546-80-2899', 8)
('548-46-9322', 8)
('548-48-3156', 8)
('549-03-9315', 8)
('549-23-9016', 8)
('549-59-1358', 8)
('549-84-7482', 8)
('549-96-4200', 8)
('550-84-8664', 8)
('551-21-3069', 8)
('552-44-5977', 8)
('554-42-2417', 8)
('554-53-3790', 8)
('554-53-8700', 8)
('556-41-6224', 8)
('556-72-8512', 8)
('556-86-3144', 8)
('556-97-7101', 8)
('558-60-5016', 8)
('558-80-4082', 8)
('559-61-5987', 8)
('559-98-9873', 8)
('560-30-5617', 8)
('560-49-6611', 8)
('562-12-5430', 8)
('563-36-9814', 8)
('563-47-4072', 8)
('563-91-7120', 8)
('565-17-3836', 8)
('565-67-6697', 8)
('565-80-5980', 8)
('565-91-4567', 8)
('566-19-5475', 8)
('566-71-1091', 8)
('568-88-3448', 8)
('568-90-5112', 8)
('569-71-4390', 8)
('569-76-2760', 8)
('571-94-0759', 8)
('573-10-3877', 8)
('573-58-9734', 8)
('573-98-8548', 8)
('574-22-5561', 8)
('574-31-8277', 8)
('574-57-9721', 8)
('574-80-1489', 8)
('575-30-8091', 8)
('575-67-1508', 8)
('576-31-4774', 8)
('577-34-7579', 8)
('578-80-7669', 8)
('582-52-8065', 8)
('583-41-4548', 8)
('583-72-1480', 8)
('584-66-4073', 8)
('584-86-7256', 8)
('585-03-5943', 8)
('585-11-6748', 8)
('585-86-8361', 8)
('585-90-0249', 8)
('586-25-0848', 8)
('587-03-7455', 8)
('587-73-4862', 8)
('588-01-7461', 8)
('588-47-8641', 8)
('589-02-8023', 8)
('590-83-4591', 8)
('592-34-6155', 8)
('592-46-1692', 8)
('593-08-5916', 8)
('593-14-4239', 8)
('593-65-1552', 8)
('593-95-4461', 8)
('594-34-4444', 8)
('595-11-5460', 8)
('595-27-4851', 8)
('595-86-2894', 8)
('595-94-9924', 8)
('596-42-3999', 8)
('597-78-7908', 8)
('598-06-7312', 8)
('598-47-9715', 8)
('600-38-9738', 8)
('602-16-6955', 8)
('602-80-9671', 8)
('603-07-0961', 8)
('604-70-6476', 8)
('605-03-2706', 8)
('605-72-4132', 8)
('605-83-1050', 8)
('606-80-4905', 8)
('607-65-2441', 8)
('607-76-6216', 8)
('608-04-3797', 8)
('608-05-3804', 8)
('608-27-6295', 8)
('608-96-3517', 8)
('609-81-8548', 8)
('610-46-4100', 8)
('612-36-5536', 8)
('613-59-9758', 8)
('616-24-2851', 8)
('616-87-0016', 8)
('617-15-4209', 8)
('618-34-8551', 8)
('620-02-2046', 8)
('622-20-1945', 8)
('624-01-8356', 8)
('626-43-7888', 8)
('627-95-3243', 8)
('628-34-3388', 8)
('628-90-8624', 8)
('629-42-4133', 8)
('630-74-5166', 8)
('631-34-1880', 8)
('631-41-3108', 8)
('632-32-4574', 8)
('632-90-0281', 8)
('633-09-3463', 8)
('633-44-8566', 8)
('633-91-1052', 8)
('634-97-8956', 8)
('635-28-5728', 8)
('635-40-6220', 8)
('636-17-0325', 8)
('636-48-8204', 8)
('636-98-3364', 8)
('638-60-7125', 8)
('639-76-1242', 8)
('640-48-5028', 8)
('640-49-2076', 8)
('641-43-2399', 8)
('641-51-2661', 8)
('641-62-7288', 8)
('641-96-3695', 8)
('642-30-6693', 8)
('642-32-2990', 8)
('642-61-4706', 8)
('643-38-7867', 8)
('645-44-1170', 8)
('645-78-8093', 8)
('647-50-1224', 8)
('648-83-1321', 8)
('648-94-3045', 8)
('649-11-3678', 8)
('649-29-6775', 8)
('650-98-6268', 8)
('651-61-0874', 8)
('651-88-7328', 8)
('651-96-5970', 8)
('652-43-6591', 8)
('652-49-6720', 8)
('655-07-2265', 8)
('655-85-5130', 8)
('656-16-1063', 8)
('656-95-9349', 8)
('658-66-3967', 8)
('659-36-1684', 8)
('659-65-8956', 8)
('660-29-7083', 8)
('662-47-5456', 8)
('662-72-2873', 8)
('663-86-9076', 8)
('664-14-2882', 8)
('665-32-9167', 8)
('665-63-9737', 8)
('667-23-5919', 8)
('667-92-0055', 8)
('668-90-8900', 8)
('669-54-1719', 8)
('670-71-7306', 8)
('670-79-6321', 8)
('672-51-8681', 8)
('674-15-9296', 8)
('674-56-6360', 8)
('676-10-2200', 8)
('676-39-6028', 8)
('677-11-0152', 8)
('678-79-0726', 8)
('679-22-6530', 8)
('685-64-1609', 8)
('686-41-0932', 8)
('687-15-1097', 8)
('687-47-8271', 8)
('689-05-1884', 8)
('689-16-9784', 8)
('690-01-6631', 8)
('692-27-8933', 8)
('692-92-5582', 8)
('695-09-5146', 8)
('695-28-6250', 8)
('695-51-0018', 8)
('696-90-2548', 8)
('698-98-5964', 8)
('699-01-4164', 8)
('699-14-3026', 8)
('699-88-1972', 8)
('700-81-1757', 8)
('701-23-5550', 8)
('701-69-8742', 8)
('702-72-0487', 8)
('702-83-5291', 8)
('704-10-4056', 8)
('704-11-6354', 8)
('704-20-4138', 8)
('704-48-3927', 8)
('706-36-6154', 8)
('707-32-7409', 8)
('709-58-4068', 8)
('710-46-4433', 8)
('711-31-1234', 8)
('712-39-0363', 8)
('714-02-3114', 8)
('715-20-1673', 8)
('716-39-1409', 8)
('717-96-4189', 8)
('718-57-9773', 8)
('719-76-3868', 8)
('719-89-8991', 8)
('720-72-2436', 8)
('721-86-6247', 8)
('722-13-2115', 8)
('725-32-9708', 8)
('725-54-0677', 8)
('725-56-0833', 8)
('725-67-2480', 8)
('725-96-3778', 8)
('726-27-2396', 8)
('726-29-6793', 8)
('727-02-1313', 16)
('727-17-0390', 8)
('727-46-3608', 8)
('727-75-6477', 8)
('728-47-9078', 8)
('728-88-7867', 8)
('729-06-2010', 8)
('729-09-9681', 8)
('729-46-7422', 8)
('730-50-9884', 8)
('730-61-8757', 8)
('730-70-9830', 8)
('731-14-2199', 8)
('731-59-7531', 8)
('731-81-9469', 8)
('732-04-5373', 8)
('732-67-5346', 8)
('732-94-0499', 8)
('733-01-9107', 8)
('733-29-1227', 8)
('733-33-4967', 8)
('734-91-1155', 8)
('735-06-4124', 8)
('735-32-9839', 8)
('737-88-5876', 8)
('740-11-5257', 8)
('740-22-2500', 8)
('741-73-3559', 8)
('742-04-5161', 8)
('743-04-1105', 8)
('743-88-1662', 8)
('744-02-5987', 8)
('744-09-5786', 8)
('744-16-7898', 8)
('744-82-9138', 8)
('745-71-3520', 8)
('745-74-0715', 8)
('746-04-1077', 8)
('746-19-0921', 8)
('746-54-5508', 8)
('746-68-6593', 8)
('746-94-0204', 8)
('747-58-7183', 8)
('748-45-2862', 8)
('749-24-1565', 8)
('749-81-8133', 8)
('750-57-9686', 8)
('750-67-8428', 8)
('751-15-6198', 8)
('751-41-9720', 8)
('751-69-0068', 8)
('752-23-3760', 8)
('755-12-3214', 8)
('756-01-7507', 8)
('756-49-0168', 8)
('756-93-1854', 8)
('759-29-9521', 8)
('759-98-4285', 8)
('760-27-5490', 8)
('760-53-9233', 8)
('760-54-1821', 8)
('760-90-2357', 8)
('761-49-0439', 8)
('764-44-8999', 8)
('765-26-6951', 8)
('766-85-7061', 8)
('767-05-1286', 8)
('767-54-1907', 8)
('767-97-4650', 8)
('770-42-8960', 8)
('775-72-1988', 8)
('776-68-1096', 8)
('777-67-2495', 8)
('777-82-7220', 8)
('778-34-2523', 8)
('778-71-5554', 8)
('778-89-7974', 8)
('779-06-0012', 8)
('779-42-2410', 8)
('781-84-8059', 8)
('782-95-9291', 8)
('783-09-1637', 8)
('784-08-0310', 8)
('784-21-9238', 8)
('785-13-7708', 8)
('785-96-0615', 8)
('786-94-2700', 8)
('787-15-1757', 8)
('787-56-0757', 8)
('787-87-2010', 8)
('788-07-8452', 8)
('788-21-5741', 8)
('789-23-8625', 8)
('790-29-1172', 8)
('790-38-4466', 8)
('793-10-3222', 8)
('794-32-2436', 8)
('794-42-3736', 8)
('795-49-7276', 8)
('796-12-2025', 8)
('796-32-9050', 8)
('797-88-0493', 8)
('799-71-1548', 8)
('800-09-8606', 8)
('801-88-0346', 8)
('802-43-8934', 8)
('802-70-5316', 8)
('803-17-8013', 8)
('803-83-5989', 8)
('804-38-3935', 8)
('805-86-0265', 8)
('807-14-7833', 8)
('807-34-3742', 8)
('808-65-0703', 8)
('809-46-1866', 8)
('809-69-9497', 8)
('810-60-6344', 8)
('811-03-8790', 8)
('811-35-1094', 8)
('815-04-6282', 8)
('815-11-1168', 8)
('816-57-2053', 8)
('816-72-8853', 8)
('817-48-8732', 8)
('817-69-8206', 8)
('821-07-3596', 8)
('821-14-9046', 8)
('824-88-3614', 8)
('825-94-5922', 8)
('826-58-8051', 8)
('827-26-2100', 8)
('827-44-5872', 8)
('827-77-7633', 8)
('828-46-6863', 8)
('828-61-5674', 8)
('829-34-3910', 8)
('829-49-1914', 8)
('830-58-2383', 8)
('831-07-6050', 8)
('831-64-0259', 8)
('831-81-6575', 8)
('832-51-6761', 8)
('834-25-9262', 8)
('834-45-5519', 8)
('834-61-8124', 8)
('834-83-1826', 8)
('835-16-0096', 8)
('836-82-5858', 8)
('837-55-7229', 8)
('838-02-1821', 8)
('838-78-4295', 8)
('840-19-2096', 8)
('840-76-5966', 8)
('841-18-8232', 8)
('841-35-6630', 8)
('842-29-4695', 8)
('842-40-8179', 8)
('843-01-4703', 8)
('843-73-4724', 8)
('845-51-0542', 8)
('845-94-6841', 8)
('846-10-0341', 8)
('847-38-7188', 8)
('848-07-1692', 8)
('848-24-9445', 8)
('848-42-2560', 8)
('848-62-7243', 8)
('848-95-6252', 8)
('849-09-3807', 16)
('850-41-9669', 8)
('851-28-6367', 8)
('851-98-3555', 8)
('852-62-7105', 8)
('852-82-2749', 8)
('853-23-2453', 8)
('856-22-8149', 8)
('856-66-2701', 8)
('857-16-3520', 8)
('857-67-9057', 8)
('859-71-0933', 8)
('859-97-6048', 8)
('860-73-6466', 8)
('860-79-0874', 8)
('861-77-0145', 8)
('862-17-9201', 8)
('862-29-5914', 8)
('862-59-8517', 8)
('864-24-7918', 8)
('865-41-9075', 8)
('865-92-6136', 8)
('866-05-7563', 8)
('866-70-2814', 8)
('866-99-7614', 8)
('867-47-1948', 8)
('868-06-0466', 8)
('868-52-7573', 8)
('868-81-1752', 8)
('869-11-3082', 8)
('870-54-3162', 8)
('870-72-4431', 8)
('870-76-1733', 8)
('871-39-9221', 8)
('871-79-8483', 8)
('873-14-6353', 8)
('873-51-0671', 8)
('873-95-4984', 8)
('875-31-8302', 8)
('875-46-5808', 8)
('877-22-3308', 8)
('878-30-2331', 8)
('880-35-0356', 8)
('880-46-5796', 8)
('881-41-7302', 8)
('882-40-4577', 8)
('883-17-4236', 8)
('883-69-1285', 8)
('884-80-6021', 8)
('885-17-6250', 8)
('885-56-0389', 8)
('886-18-2897', 8)
('886-54-6089', 8)
('886-77-9084', 8)
('887-42-0517', 8)
('888-02-0338', 8)
('889-04-9723', 8)
('891-01-7034', 8)
('891-58-8335', 8)
('892-05-6689', 8)
('894-41-5205', 8)
('895-03-6665', 8)
('895-66-0685', 8)
('896-34-0956', 8)
('898-04-2717', 8)


# SUBMIT FORMAT

* **<-zip>**
  - **studentID_name_surname_hw1.ipynb**

# PLAGIARISM

All work on assignments must be done individually. You are encouraged to discuss the given assignments with your classmates, but these discussions should be carried out in an abstract way. That is, discussions related to a particular solution to a specific probem (either in actual code or in pseudocode) will not be tolerated. In short, turning in someone else’s work (including work available on the internet), in whole or in part, as your own will be considered as a violation of academic integrity. Please note that the former conditions also hold for the material attained using AI tools, including ChatGPT, GitHub Copilot, etc.